FROM ubuntu:bionic

LABEL authors="Gabriele Baldoni"

RUN apt-get update -qq && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install libev4 libssl1.1 curl

RUN curl -Lo /tmp/zenohd.deb https://github.com/eclipse-fog05/fog05/releases/download/v0.2.0/zenoh_0.3.0-1_ubuntu.18.04_arm64.deb
RUN dpkg -i /tmp/zenohd.deb

CMD /etc/zenoh/zenohd -P "/etc/zenoh/yaks-plugin.cmxs -s /**" -vv

